services:
  db:
    image: postgres:15
    container_name: ${DB_CONTAINER_NAME}
    env_file: .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    depends_on:
      - db
    env_file: .env
    ports:
      - "${APP_PORT}:8080"
    restart: always

volumes:
  pgdata: